# The URL the site will be built for
base_url = "https://gekkio.fi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

[markdown]

[markdown.highlighting]
theme = "github-light"

[extra]
# Put all your custom variables here
